name: CommonPlam

on:
  push:
    branches:
      - develop
      
permissions: 
      id-token: write
      
jobs:
  directories:
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.set-dirs.outputs.dir }}
    steps:
      - uses: actions/checkout@v2
      - id: set-dirs
        run: echo "::set-output name=dir::$(ls -d */*/ | jq -R -s -c 'split("\n")[:-1]')"

  plan:
    name: Plan
    runs-on: ubuntu-latest
    needs: [directories]
    timeout-minutes: 5
    strategy:
      matrix:
        dir: ${{fromJson(needs.directories.outputs.dir)}}        
    steps:
      - uses: actions/checkout@v2
        name: Checkout
    
      - name: Check diff
        id: diff
        uses: technote-space/get-diff-action@v4.0.2
        with:
          PATTERNS: |
            ${{ matrix.dir }}/modules/**/*.tf
            ${{ matrix.dir }}/*.tf
      
      - name: Configure AWS Credentials
        if: steps.diff.outputs.diff
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::166313796795:role/test-gha
    
      - name: Setup terraform
        if: steps.diff.outputs.diff
        uses: hashicorp/setup-terraform@v1
      
      - name: Terraform fmt
        id: fmt
        if: steps.diff.outputs.diff
        working-directory: ${{ matrix.dir }}
        run: terraform fmt -check
        continue-on-error: true
      
      - name: Terraform Init
        id: init
        if: steps.diff.outputs.diff
        working-directory: ${{ matrix.dir }}
        run: terraform init -backend-config="key=${{ github.repository }}/${{ matrix.dir }}/terraform.tfstate"
      
      - name: Terraform Validate
        id: validate
        if: steps.diff.outputs.diff
        working-directory: ${{ matrix.dir }}
        run: terraform validate -no-color
      
      - name: Terraform Plan
        id: plan
        if: steps.diff.outputs.diff
        working-directory: ${{ matrix.dir }}
        run: terraform plan -no-color
        continue-on-error: true

      - name: Store ETag of tfstate file
        id: etag
        if: steps.diff.outputs.diff
        working-directory: ${{ matrix.dir }}
        shell: bash
        env:
          EMAIL: ${{ github.event.pusher.email }}
          USER: ${{ github.event.pusher.name }}
        run: |
          aws s3api head-object --bucket miyashita-tfstate --key S3/terraform.tfstate | jq -r .ETag > ./etag-tfstate.txt
          git config --local user.email "${env.EMAIL}"
          git config --local user.name "${env.USER}"
          git add ./etag-tfstate.txt
          git commit -m "add: Store ETag of tfstate file"
        
      - name: Push changes
        uses: ad-m/github-push-action@master
        id: push
        if: steps.diff.outputs.diff
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}