name: test

on:
  push:
    branches:
    - main
  pull_request:
jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    steps:
    - name: print env
      env:
        INFO: ${{ toJson(github.event) }}
      run: |
        echo "$INFO"
    - name: check esist pr
      env:
        REPO: ${{ github.repository }}
        PR: ${{ github.event.inputs.prNumber }}
      run: |
        curl -s -I -u miyamiyab:${{ secrets.GH_PAT }} \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.inputs.prNumber }} \
            -o /dev/null -w '%{http_code}\n'
