name: test

on:
  push:
    branches:
      - develop
      
jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    steps:
    - name: print env
      run: |
        echo ${{ github.event.commits }}
    - name: print add files
      if:  github.event.commits[0]['added']
      run: |
        echo ${{ github.event.commits }}
        echo ${{ github.event.commits[0]['added']}}
    - name: print modify files
      if: github.event.commits[0]['modified']
      run: |
        echo ${{ github.event.commits }}
        echo ${{ github.event.commits[0]['modified']}}
