name: test

on:
  push:
    branches:
      - develop
      
jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    steps:
    - name: print env
      run: |
        echo ${{ github.event.commits }}
        echo ${{ github.event.commits[0][added]}}
        echo ${{ github.event.commits[0][modified]}}
