name: test

on:
  push:
    branches:
      - develop
      
jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    steps:
    - name: print env
      env:
        COMMIT_INFO: ${{ toJson(github.event.commits) }}
      run: |
        echo "$COMMIT_INFO"
