name: test

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      prNumber:
        description: The pull request number that failed.
        required: true
        type: number
      
jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    steps:
    - name: print env
      env:
        INFO: ${{ toJson(github.event) }}
      run: |
        echo "$INFO"
    - name: check esist pr
      env:
        REPO: ${ github.repository }
        PR: ${ github.event.inputs.prNumber }
      run: |
        curl -i -u miyamiyab:${{ secrets.GH_PAT }} \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${process.env.REPO}/issues/${process.env.PR}
