name: test-pr

on:
  pull_request:
    branches:
      - main
  push:
      
jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    steps:
    - name: print env
      env:
        INFO: ${{ toJson(github.event) }}
      run: |
        echo ${{ github.event_name }}
        echo "$INFO"
