name: test

on:
  pull-request:
    branches:
      - main
      
jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    steps:
    - name: print env
      env:
        INFO: ${{ toJson(github.event) }}
      run: |
        echo "$INFO"
